import { lazy } from "react";

import {
  HeroEcommerce,
  FeaturedCategories,
  BestSellers,
  NewArrivals,
  FlashSale,
  FeaturedProducts,
  WhyChooseUs,
  Testimonials,
  BrandShowcase,
  NewsletterSignup,
  InstagramFeed,
  FAQPreview,
  ContactPreview,
  StoreLocator,
  ShopHero,
  ProductFilters,
  ProductGrid,
  Breadcrumbs,
  ProductDetails,
  ProductReviews,
  RelatedProducts,
  RecentlyViewed,
  PageHero,
  CategoryGrid,
  AboutStory,
  AboutValues,
  TeamSection,
  CTABanner,
  ContactInfo,
  ContactForm,
  MapEmbed,
  BlogGrid,
  FAQAccordion,
  OrderTracking,
  WishlistGrid,
  CartItems,
  CartSummary,
  CheckoutForm,
  LegalContent,
} from "@/component-library/Ecommerce";

const ComponentRegistry: Record<string, React.ComponentType<any>> = {
  Navbar1: lazy(() => import("@/component-library/Navbar/Navbar1")),
  Navbar2: lazy(() => import("@/component-library/Navbar/Navbar2")),
  Navbar3: lazy(() => import("@/component-library/Navbar/Navbar3")),
  Hero1: lazy(() => import("@/component-library/Hero/Hero1")),
  Hero2: lazy(() => import("@/component-library/Hero/Hero2")),
  Hero3: lazy(() => import("@/component-library/Hero/Hero3")),
  About1: lazy(() => import("@/component-library/About/About1")),
  About2: lazy(() => import("@/component-library/About/About2")),
  Services1: lazy(() => import("@/component-library/Services/Services1")),
  Services2: lazy(() => import("@/component-library/Services/Services2")),
  Gallery1: lazy(() => import("@/component-library/Gallery/Gallery1")),
  Gallery2: lazy(() => import("@/component-library/Gallery/Gallery2")),
  Portfolio1: lazy(() => import("@/component-library/Portfolio/Portfolio1")),
  Portfolio2: lazy(() => import("@/component-library/Portfolio/Portfolio2")),
  Pricing1: lazy(() => import("@/component-library/Pricing/Pricing1")),
  Pricing2: lazy(() => import("@/component-library/Pricing/Pricing2")),
  FAQ1: lazy(() => import("@/component-library/FAQ/FAQ1")),
  FAQ2: lazy(() => import("@/component-library/FAQ/FAQ2")),
  Testimonials1: lazy(() => import("@/component-library/Testimonials/Testimonials1")),
  Testimonials2: lazy(() => import("@/component-library/Testimonials/Testimonials2")),
  CTA1: lazy(() => import("@/component-library/CTA/CTA1")),
  CTA2: lazy(() => import("@/component-library/CTA/CTA2")),
  Contact1: lazy(() => import("@/component-library/Contact/Contact1")),
  Contact2: lazy(() => import("@/component-library/Contact/Contact2")),
  Footer1: lazy(() => import("@/component-library/Footer/Footer1")),
  Footer2: lazy(() => import("@/component-library/Footer/Footer2")),
  Footer3: lazy(() => import("@/component-library/Footer/Footer3")),
  HeroEcommerce,
  FeaturedCategories,
  BestSellers,
  NewArrivals,
  FlashSale,
  FeaturedProducts,
  WhyChooseUs,
  Testimonials,
  BrandShowcase,
  NewsletterSignup,
  InstagramFeed,
  FAQPreview,
  ContactPreview,
  StoreLocator,
  ShopHero,
  ProductFilters,
  ProductGrid,
  Breadcrumbs,
  ProductDetails,
  ProductReviews,
  RelatedProducts,
  RecentlyViewed,
  PageHero,
  CategoryGrid,
  AboutStory,
  AboutValues,
  TeamSection,
  CTABanner,
  ContactInfo,
  ContactForm,
  MapEmbed,
  BlogGrid,
  FAQAccordion,
  OrderTracking,
  WishlistGrid,
  CartItems,
  CartSummary,
  CheckoutForm,
  LegalContent,
};

export default ComponentRegistry;
