import React, { Suspense, useState, useEffect } from "react";
import ComponentRegistry from "./ComponentRegistry";

interface Section {
  id: string;
  component: string;
  props: Record<string, any>;
  order: number;
}

interface Page {
  slug: string;
  title: string;
  sections: Section[];
}

interface WebsiteData {
  name?: string;
  pages: Page[];
  theme?: {
    primaryColor?: string;
    secondaryColor?: string;
    backgroundColor?: string;
    foregroundColor?: string;
    background?: string;
    textColor?: string;
    mutedColor?: string;
    borderColor?: string;
    fontStyle?: string;
    fontFamily?: string;
  };
  navigation?: {
    items?: Array<{ label?: string; href?: string; page?: string; slug?: string }>;
  };
  footer?: {
    copyright?: string;
    links?: Array<{ label?: string; href?: string }>;
  };
}

interface SectionRendererProps {
  component: string;
  props: Record<string, any>;
}

export const SectionRenderer: React.FC<SectionRendererProps> = ({
  component,
  props,
}) => {
  const Component = ComponentRegistry[component];

  if (!Component) {
    return (
      <div className="p-4 bg-muted text-muted-foreground text-sm text-center">
        Component "{component}" not found
      </div>
    );
  }

  return (
    <Suspense
      fallback={
        <div className="p-8 flex justify-center">
          <div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" />
        </div>
      }
    >
      <Component {...props} />
    </Suspense>
  );
};

interface PageRendererProps {
  page: Page;
}

export const PageRenderer: React.FC<PageRendererProps> = ({ page }) => {
  const sorted = [...page.sections].sort((a, b) => a.order - b.order);

  return (
    <div>
      {sorted.map((section) => (
        <SectionRenderer
          key={section.id}
          component={section.component}
          props={section.props}
        />
      ))}
    </div>
  );
};

interface WebsiteRendererProps {
  data: WebsiteData;
  currentPage?: string;
  onNavigatePage?: (slug: string) => void;
}

const hexToRgb = (hex: string) => {
  const normalized = hex.replace("#", "");
  const full = normalized.length === 3
    ? normalized.split("").map((char) => char + char).join("")
    : normalized;

  const value = Number.parseInt(full, 16);
  return {
    r: (value >> 16) & 255,
    g: (value >> 8) & 255,
    b: value & 255,
  };
};

const getReadableTextColor = (hex: string) => {
  const { r, g, b } = hexToRgb(hex);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.6 ? "#111827" : "#ffffff";
};

const hexWithAlpha = (hex: string, alpha: number) => {
  const { r, g, b } = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};

const WebsiteRenderer: React.FC<WebsiteRendererProps> = ({
  data,
  currentPage = "home",
  onNavigatePage,
}) => {
  const page = data.pages.find((p) => p.slug === currentPage) || data.pages[0];
  const theme = data.theme;

  const primaryColor = theme?.primaryColor || "#2563EB";
  const secondaryColor = theme?.secondaryColor || "#1E40AF";
  const backgroundColor = theme?.backgroundColor || theme?.background || "#ffffff";
  const foregroundColor = theme?.foregroundColor || theme?.textColor || "#111827";
  const borderColor = theme?.borderColor || "#e5e7eb";
  const mutedColor = theme?.mutedColor || "#f3f4f6";
  const fontFamily = theme?.fontFamily || theme?.fontStyle || "Inter";

  const primaryForeground = getReadableTextColor(primaryColor);
  const secondaryForeground = getReadableTextColor(secondaryColor);
  const accentColor = (theme as any)?.accentColor || secondaryColor;
  const primarySoft = (theme as any)?.primarySoft || hexWithAlpha(primaryColor, 0.12);
  const secondarySoft = (theme as any)?.secondarySoft || hexWithAlpha(secondaryColor, 0.12);
  const surfaceStrong = (theme as any)?.surfaceStrong || hexWithAlpha(primaryColor, 0.2);
  const gradientFrom = (theme as any)?.gradientFrom || primaryColor;
  const gradientTo = (theme as any)?.gradientTo || secondaryColor;
  const ringGlow = (theme as any)?.ringGlow || hexWithAlpha(primaryColor, 0.35);
  const siteName = data.name || "My Store";

  // Cart counter that reacts to "cart:add" events dispatched by product cards
  const [cartCount, setCartCount] = useState(0);
  useEffect(() => {
    const handler = () => setCartCount((c) => c + 1);
    window.addEventListener("cart:add", handler);
    return () => window.removeEventListener("cart:add", handler);
  }, []);

  const AVAILABLE_SLUGS = data.pages.map((p) => p.slug);

  // Map common nav hrefs/labels to the actual page slugs generated by the spec.
  const slugAliases: Record<string, string[]> = {
    about: ["about", "about_us", "about-us", "our_story", "our-story", "aboutus"],
    contact: ["contact", "contact_us", "contact-us", "get_in_touch", "contactus"],
    "book-appointment": ["book_appointment", "book-appointment", "book_now", "book-now", "bookappointment"],
    "track-order": ["track_order", "track-order", "trackorder"],
    "product-details": ["product_details", "product-details", "details"],
    "privacy-policy": ["privacy_policy", "privacy-policy"],
    "terms-conditions": ["terms_conditions", "terms-conditions"],
    "refund-policy": ["refund_policy", "refund-policy"],
  };

  const resolveSlug = (value?: string): string | undefined => {
    const raw = (value || "")
      .replace(/^\/+/, "")
      .replace(/\.html$/, "")
      .toLowerCase();
    if (!raw) return undefined;
    if (AVAILABLE_SLUGS.includes(raw)) return raw;
    const normalized = raw.replace(/-/g, "_");
    if (AVAILABLE_SLUGS.includes(normalized)) return normalized;
    for (const aliases of Object.values(slugAliases)) {
      if (aliases.includes(raw) || aliases.includes(normalized)) {
        const match = AVAILABLE_SLUGS.find((s) => aliases.includes(s));
        if (match) return match;
      }
    }
    return undefined;
  };

  const rawNavItems: Array<{ label?: string; href?: string; page?: string; slug?: string }> =
    data.navigation?.items?.length
      ? data.navigation.items
      : data.pages.map((p) => ({ label: p.title, page: p.slug }));
  const navItems = rawNavItems.map((item) => {
    const explicit = item.page || item.slug;
    const page = resolveSlug(explicit) || resolveSlug(item.href) || "";
    return {
      label: item.label || "Page",
      href: item.href || `#${page}`,
      page,
    };
  });

  const themeStyle = {
    "--color-primary": primaryColor,
    "--color-primary-foreground": primaryForeground,
    "--color-secondary": secondaryColor,
    "--color-secondary-foreground": secondaryForeground,
    "--color-background": backgroundColor,
    "--color-foreground": foregroundColor,
    "--color-muted": mutedColor,
    "--color-muted-foreground": "#6b7280",
    "--color-border": borderColor,
    "--color-card": backgroundColor,
    "--color-card-foreground": foregroundColor,
    fontFamily: `${fontFamily}, Inter, system-ui, sans-serif`,
  } as React.CSSProperties;

  const previewOverrides = `
    .theme-preview {
      --theme-primary: ${primaryColor};
      --theme-primary-foreground: ${primaryForeground};
      --theme-secondary: ${secondaryColor};
      --theme-secondary-foreground: ${secondaryForeground};
      --theme-background: ${backgroundColor};
      --theme-foreground: ${foregroundColor};
      --theme-muted: ${mutedColor};
      --theme-border: ${borderColor};
      --theme-card: ${backgroundColor};
      --theme-accent: ${accentColor};
      --theme-primary-soft: ${primarySoft};
      --theme-secondary-soft: ${secondarySoft};
      --theme-surface-strong: ${surfaceStrong};
      --theme-gradient-from: ${gradientFrom};
      --theme-gradient-to: ${gradientTo};
      --theme-ring-glow: ${ringGlow};

      /* Legacy CSS variables used by PetStore / Automotive / HomeServices components */
      --c1: ${primaryColor};
      --ctx: ${foregroundColor};
      --ctx2: ${mutedColor};
      --bg: ${backgroundColor};
      --bgc: ${mutedColor};
      --bdr: ${borderColor};
      --bgd: ${mutedColor};
    }

    .theme-preview { background-color: var(--theme-background); color: var(--theme-foreground); }
    .theme-preview {
      font-family: ${fontFamily}, Inter, system-ui, sans-serif;
      scroll-behavior: smooth;
    }
.theme-preview section { position: relative; }
    .theme-preview h1, .theme-preview h2, .theme-preview h3, .theme-preview h4 {
      letter-spacing: -0.02em;
    }

    /* Tighten vertical rhythm between stacked section components so the
       page feels cohesive instead of having huge gaps between blocks. */
    .theme-preview section {
      padding-top: 2.5rem !important;
      padding-bottom: 2.5rem !important;
    }
    .theme-preview section + section {
      margin-top: 0 !important;
    }
    .theme-preview section:first-child {
      padding-top: 0.5rem !important;
    }
    .theme-preview section:last-child {
      padding-bottom: 0.5rem !important;
    }
    .theme-preview .text-primary { color: var(--theme-primary) !important; }
    .theme-preview a[href] { transition: all 0.2s ease; }

    /* Primary / Secondary surfaces */
    .theme-preview .bg-primary { background-color: var(--theme-primary) !important; }
    .theme-preview .text-primary { color: var(--theme-primary) !important; }
    .theme-preview .border-primary { border-color: var(--theme-primary) !important; }
    .theme-preview .ring-primary { --tw-ring-color: var(--theme-primary) !important; }
    .theme-preview .text-primary-foreground { color: var(--theme-primary-foreground) !important; }
    .theme-preview .bg-primary-foreground { background-color: var(--theme-primary-foreground) !important; }
    .theme-preview .bg-secondary { background-color: var(--theme-secondary) !important; }
    .theme-preview .text-secondary { color: var(--theme-secondary) !important; }
    .theme-preview .bg-secondary-foreground { background-color: var(--theme-secondary-foreground) !important; }
    .theme-preview .text-secondary-foreground { color: var(--theme-secondary-foreground) !important; }

    /* Soft / tinted surfaces */
    .theme-preview .bg-primary\/5, .theme-preview .bg-primary\/10 { background-color: var(--theme-primary-soft) !important; }
    .theme-preview .bg-secondary\/5, .theme-preview .bg-secondary\/10 { background-color: var(--theme-secondary-soft) !important; }
    .theme-preview .bg-accent { background-color: var(--theme-accent) !important; }
    .theme-preview .text-accent { color: var(--theme-accent) !important; }
    .theme-preview .from-primary { --tw-gradient-from: var(--theme-gradient-from) !important; }
    .theme-preview .to-primary { --tw-gradient-to: var(--theme-gradient-to) !important; }
    .theme-preview .to-secondary { --tw-gradient-to: var(--theme-gradient-to) !important; }
    .theme-preview .from-primary\/10 { --tw-gradient-from: color-mix(in srgb, var(--theme-primary) 10%, transparent) !important; }
    .theme-preview .to-secondary\/10 { --tw-gradient-to: color-mix(in srgb, var(--theme-secondary) 10%, transparent) !important; }

    /* Background / foreground */
    .theme-preview .bg-background { background-color: var(--theme-background) !important; }
    .theme-preview .text-foreground { color: var(--theme-foreground) !important; }
    .theme-preview .bg-muted { background-color: var(--theme-muted) !important; }
    .theme-preview .bg-muted\/50 { background-color: color-mix(in srgb, var(--theme-muted) 50%, white) !important; }
    .theme-preview .text-muted-foreground { color: #6b7280 !important; }
    .theme-preview .border-border { border-color: var(--theme-border) !important; }
    .theme-preview .bg-card { background-color: var(--theme-card) !important; }
    .theme-preview .bg-card\/70 { background-color: color-mix(in srgb, var(--theme-card) 70%, white) !important; }
    .theme-preview .text-card-foreground { color: var(--theme-foreground) !important; }
    .theme-preview .bg-surfacestrong { background-color: var(--theme-surface-strong) !important; }
    .theme-preview .shadow-primary\/20 { box-shadow: 0 20px 40px -12px var(--theme-primary) !important; }
    .theme-preview .shadow-primary\/10 { box-shadow: 0 10px 25px -8px var(--theme-primary) !important; }
    .theme-preview .shadow-glow { box-shadow: 0 0 40px var(--theme-ring-glow) !important; }
    .theme-preview .ring-glow { box-shadow: 0 0 0 4px var(--theme-ring-glow) !important; }
    .theme-preview .text-glow { text-shadow: 0 0 20px var(--theme-ring-glow) !important; }

    /* Buttons */
    .theme-preview .btn-gradient {
      background-image: linear-gradient(135deg, var(--theme-gradient-from), var(--theme-gradient-to)) !important;
      color: var(--theme-primary-foreground) !important;
    }
    .theme-preview .btn-primary {
      background-color: var(--theme-primary) !important;
      color: var(--theme-primary-foreground) !important;
    }
    .theme-preview .btn-primary:hover {
      background-color: var(--theme-gradient-to) !important;
    }
    .theme-preview .btn-outline {
      border-color: var(--theme-border) !important;
      color: var(--theme-foreground) !important;
      background: transparent !important;
    }
    .theme-preview .btn-outline:hover {
      background-color: var(--theme-muted) !important;
      border-color: var(--theme-primary) !important;
      color: var(--theme-primary) !important;
    }
  `;

  if (!page) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        No pages found in website spec
      </div>
    );
  }

  return (
    <div className="theme-preview" style={themeStyle}>
      <style>{previewOverrides}</style>
      <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8">
          <button
            type="button"
            onClick={() => onNavigatePage?.(page.slug)}
            className="flex items-center gap-2 text-left text-lg font-bold tracking-tight text-foreground"
          >
            <span
              className="flex h-9 w-9 items-center justify-center rounded-xl text-sm font-black"
              style={{
                backgroundImage: `linear-gradient(135deg, ${gradientFrom}, ${gradientTo})`,
                color: primaryForeground,
              }}
            >
              {siteName.charAt(0).toUpperCase()}
            </span>
            <span>{siteName}</span>
          </button>
          <nav className="hidden items-center gap-1 md:flex">
            {navItems.map((item) => {
              const isActive = item.page === currentPage;
              if (onNavigatePage && item.page) {
                return (
                  <button
                    key={item.href || item.page}
                    type="button"
                    onClick={() => onNavigatePage(item.page!)}
                    className={`rounded-xl px-4 py-2 text-sm font-medium transition-all ${isActive
                      ? "bg-primary/10 text-primary"
                      : "text-muted-foreground hover:bg-muted hover:text-foreground"
                      }`}
                  >
                    {item.label}
                  </button>
                );
              }
              return (
                <a key={item.href || item.page} href={item.href} className="rounded-xl px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground">
                  {item.label}
                </a>
              );
            })}
          </nav>
          {/* Cart badge */}
          <div className="relative">
            <span
              className="flex h-10 w-10 items-center justify-center rounded-xl border border-border/70"
              style={{ backgroundColor: primarySoft, color: primaryColor }}
              title="Cart"
            >
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 100 4 2 2 0 000-4z" /></svg>
            </span>
            {cartCount > 0 && (
              <span className="absolute -right-1.5 -top-1.5 flex h-5 min-w-5 items-center justify-center rounded-full bg-destructive px-1 text-[11px] font-bold text-white shadow-lg">
                {cartCount}
              </span>
            )}
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
        <PageRenderer page={page} />
      </main>

      <footer
        className="border-t border-border/70"
        style={{
          backgroundImage: `linear-gradient(135deg, ${gradientFrom}14, ${backgroundColor} 40%, ${gradientTo}14)`,
        }}
      >
        <div className="mx-auto flex max-w-7xl flex-col gap-4 px-6 py-8 text-sm text-muted-foreground lg:flex-row lg:items-center lg:justify-between lg:px-8">
          <div>
            <p className="font-semibold text-foreground">{siteName}</p>
            <p>{data.footer?.copyright || `© ${new Date().getFullYear()} ${siteName}. All rights reserved.`}</p>
          </div>
          <div className="flex flex-wrap gap-4">
            {(data.footer?.links || navItems).map((item) => {
              const footerItem = item as { label?: string; href?: string; page?: string; slug?: string };
              const footerPage = resolveSlug(footerItem.page || footerItem.slug) || resolveSlug(footerItem.href) || "";
              if (onNavigatePage && footerPage && data.pages.some((p) => p.slug === footerPage)) {
                return (
                  <button
                    key={footerItem.href || footerItem.label}
                    type="button"
                    onClick={() => onNavigatePage(footerPage)}
                    className="transition-colors hover:text-primary cursor-pointer"
                  >
                    {footerItem.label}
                  </button>
                );
              }
              return (
                <a key={footerItem.href || footerItem.label} href={footerItem.href} className="transition-colors hover:text-primary">
                  {footerItem.label}
                </a>
              );
            })}
          </div>
        </div>
      </footer>
    </div>
  );
};

export default WebsiteRenderer;
